### ISSUE TITLE
Suggestions / Tips

### ISSUE THREAD

**Issue by Esie-Eyen** [Esie-Eyen/BSMods#2]
Title explains everything.

**Comment by Benefit-Zebra** [comment]
@Esie-Eyen

Can you make a new powerup and add it to bombsquad as how snoBallz were added (without changing game-in-scripts).

The powerup will be blackhole.

It will suck inside everything (Including flag , players , puck and other powerups nearby excluding , the player who has taken the powerup).

Since bombsquad has less number of powerups these extra powerup will make the gameplay exciting.

**Comment by Esie-Eyen** [comment]
@Benefit-Zebra I already make some powerups back then, where if you get this "Zombie Powerup" 3 zombies will spawn. Unfortunately that was created by editing in-game scripts, and here I am still waiting and learning on how it is possible to make new powerup in BS without changing in-game scripts.

**Comment by Benefit-Zebra** [comment]
@Esie-Eyen

Ok Try when you learn it.

**Comment by Esie-Eyen** [comment]
Sorry I dont have the file, when I started and upload that video. A few days ago I quitted playing BS. You can search it in youtube, "BombSquad | Zombie Powerup Mod for BombSquad"

**Comment by Esie-Eyen** [comment]
@Benefit-Zebra Join my [Discord](https://discord.gg/kSvUkmS). We can talk easily there.

**Comment by Esie-Eyen** [comment]
@Benefit-Zebra @MattZ45986 Can you check out my new mod? And tell me how was it.

**Blast Powerup Mod**
- A new powerup that looks like a tnt, if you pick it up bomb blast will occur. It changes everytime (ice, normal, sticky and tnt) as well as the radius (0.5, 1.0, 1.5 and 2.0), I put a screen message for it to let youknow what TYPE and RADIUS did you get.

**Comment by Benefit-Zebra** [comment]
@Esie-Eyen

It is not working as snowypowerup.py crashes with it.

**Comment by Esie-Eyen** [comment]
@Benefit-Zebra You need ro remove BuddyBunny and SnowyPowerup.

**Comment by Benefit-Zebra** [comment]
@Esie-Eyen

Instead of touching tnt , you should turn it into a tnt bomb which we can use to throw at enemy and it should occur different blast like ice or impact at every throw.

First :

Make a separate File for tnt bomb like tntbomb.py

Second :

Add it to snowypowerup.py so all three (Bunny ; Snowball ; And Tnt bomb) will be there.

Third :

And upload both Tnt bomb file and updated snowypowerup.py with tnt bomb for test and download.

**Comment by Benefit-Zebra** [comment]
@Esie-Eyen Please Try to make it.

**Comment by Esie-Eyen** [comment]
@Benefit-Zebra I just finish making a **Mix Powerup** and renamed my mod into **Extra Powerups Mod**. Currently there are 2 new powerups only...

About the merging the SnowyPowerup and ExtraPowerup, I will work on it now.

**Comment by Benefit-Zebra** [comment]
@Esie-Eyen Ok.

Thank you very much.


After making Health and Curse bomb powerups and Flying Race can anyone make this mods :

1st

It will be "SnowStorm.py"

In this mod , snow is dropen from the sky like from up in Football stadium . Sometimes Ice cubes will be fallen , if ice cubes when get hit to player , the player will freeze.

And create some safe zone were snow or ice cubes will not drop and the safe zones will always change its position randomly.

2nd

It will be electric bomb.

This bomb , when thrown at enemy , will causes electric spark or lightning bolt from sky which will drop on enemy on which it is thrown and the players health will decrease and the player will become static for some time wuth countdown.

**Comment by Benefit-Zebra** [comment]
@Esie-Eyen

Try to make both ideas.

We should try everytime so we can improve.

**Comment by Esie-Eyen** [comment]
@Benefit-Zebra Just finished my **Drunk Bomb Mod**

**Drunk Bomb** is a bomb that is sticky and look like a impact bomb, but when it explodes the players in the range will fall down.

- **_How the Drunk Bomb works?_** 
1. When it explodes the player will fall down for **1.5**  seconds.
2. After **2** seconds, the player will fall down again for **1.5** seconds.
3. After **4** seconds, the player will fall down again but for **3** seconds which is longer time than the first two.

(  "This is not available as a single script mod, since I edited the bsSpaz, bsBomb and bsPowerup to make this. It means I cannot upload it like the Extra Powerups mod." )

**Comment by Benefit-Zebra** [comment]
@Esie-Eyen

It's Ok as we don't change script inside bombsquad and can be played with friends.

**Comment by Esie-Eyen** [comment]
@Benefit-Zebra I will wait until someone did it. Someone who could make a new Bomb without editing in-game scripts.

**Comment by Benefit-Zebra** [comment]
@Esie-Eyen

But the bomb you have created uses script as ExtraPowerup.As script is outside it enables is to play with friends.

**Comment by Esie-Eyen** [comment]
@Benefit-Zebra Do you have more ideas for a Bomb or a Powerup? I just finish making 2 bombs right now.

**Comment by Benefit-Zebra** [comment]
@Esie-Eyen

1st

A powerup which will create a shortcut way or road between the map for the player.

2nd

A bomb when thrown at enemy will make him dizzy and will make night mode when blast.

**Comment by Esie-Eyen** [comment]
@Benefit-Zebra You need to make the bomb or powerup to be compatible for a serious gameplay. i dont know whats the point of making the night mode. And what do you mean by merging the two maps? I think I cant do that since Im only mastering coding not modelling maps.

**Comment by Benefit-Zebra** [comment]
@Esie-Eyen Subscribed

**Comment by Benefit-Zebra** [comment]
@Esie-Eyen

Like new powerups , Can you create new Bombs without changing in-game scripts.

**Comment by Benefit-Zebra** [comment]
@MattZ45986 @Esie-Eyen

Since I am not a modder , I cannot understand how to do all that things.

Please can you create them ?

**Comment by MattZ45986** [comment]
@Benefit-Zebra, understandably, we cannot expect you to know how to do things that are far beyond your reach, but I would strongly encourage you to learn to mod.  It seems that you are very interested in it all and have no lack of creative ideas.  All you need to know is how to code in Python, and then get some experience with the game processes.  It's very rewarding, and if you start to make mods, I would be delighted to take a look at them, test them out, and if they're pretty good (though it may take a try or two) I will put them on the official mod manager for all to enjoy.  They need more traffic over there, and I think if you dedicated yourself, you would make a great modder.  If you are interested, Code Academy has a great beginner program, and Stack Exchange will meet all your technical needs.  If you have any questions specific to Bombsquad, I'm always here.  Let me know what you think.

(Also, if you want to make a repository, that wouldn't be a bad idea, because I'm not sure cluttering up @Esie-Eyen's Suggestions Issue is the best way to communicate)

**Comment by Benefit-Zebra** [comment]
@MattZ45986 @Esie-Eyen

Python programming teachings are not available in my country.

Can you please make the extra bomb one mod for me?

**Comment by MattZ45986** [comment]
@Benefit-Zebra, 

Interesting! If you don't mind me asking, where do you live? Because there are instructions all over the internet, so there is bound to be something available.  Nevertheless, if it is truly inconvenient for you to learn to code, that is a shame, but I will see what I can do with the mod.

**Comment by Benefit-Zebra** [comment]
@MattZ45986

I live in India and where do you live?

**Comment by Mikahael** [comment]
bro, i can make a few bombs for you. I'm not a much modder buy know somethings
