### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Esie-Eyen** [Esie-Eyen/BSMods#3]
Thing that needs help.

**Comment by Esie-Eyen** [comment]
@MattZ45986 I think I already figured how to make the character change its bombs, I try putting some powerups right after they grab the flags. The only problem right now, is how can I change the behavior of the controls. I want players to be a PUNCH ONLY or BOMB ONLY characters, im still learning on how to do it.

**Comment by MattZ45986** [comment]
@Esie-Eyen, you will see in my Chess mod that when I spawn the different pieces I give different controls to players.  Check it out, because that is how you make spazzes only punch.  Use `spaz.connectControlsToPlayer(enablePunch=True,enableBomb=False,enablePickUp=False)` 
and it should work! Ask me if you need help.  P.S. I'm curious what you're working on. It sounds interesting.

**Comment by Esie-Eyen** [comment]
@MattZ45986 After seeing your code on **Flag Day**, I just learn that I dont need to make a custom spaz anymore to change or modify the controls.

**Comment by Esie-Eyen** [comment]
@MattZ45986 Its been a while, so Im asking some things.

- As you can see in bsPowerup when the `self.node` is written it means it talks about the Powerup Box. How can I make a node for the Receiver/Player? I cant edit bsSpaz since I only want to edit bsPowerup. Most of the core codes of Powerup is in the bsSpaz, bsSpaz file is too big so I want to ediy only the bsPowerup. So how can I trigger the Player/Receiver node? I try `self.node` and it doesnt work since it talks about the Powerup Box.

**Comment by MattZ45986** [comment]
@Esie-Eyen, It kind of depends on what you want to do with the Spaz you
need a reference for.  It also depends on what kind of edits you are trying
to make.  I'm assuming you don't want to edit the original bsSpaz script
since you said it's too large.  What you could do is not even mess with the
original file, but instead override the methods in the bs.Spaz() class.  If
you want to know what I'm talking about check out the snowyPowerup.py
on @Mrmaxmeier 's mod manager.  He directly assigns his code to the
bsPowerup module in the last two lines, which takes care of the needed code
changes.  You can do the same with the bsSpaz files since it would be much
easier than trying to get a reference of the spaz node from the powerup
collision information in the powerup script. If anything doesn't make
sense, please ask.  It's funny that you should ask me about this problem
because I've been working on @Benefit-Zebra 's powerup ideas, and I ran
into this, too.  Anyway, hope it helps, and thanks for all the great
questions.
